### PR TITLE
Featers

### PR DESCRIPTION
**Pull request by AhmadiGu**
This file main point is on linters  so can you have a look to my style also

### CODE REVIEW

**Review by GiuseppeTG — CHANGES_REQUESTED** [review]
Hi @AhmadiGu 👋 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

Alt Text

## Highlights
✅ Good style
✅ No linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Commit messages should start with a capital letter and imperative tense. Is a standard 🤓 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by GiuseppeTG** [comment]
- [ ] Feel free to use [Microverse Readme Template](https://github.com/microverseinc/readme-template). Your repo readme will look more professional. It uses also a link to your Licence. You can read more about this [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository). Kindly edit the readme template so that it contains the info about your project. 😄

**Comment by GiuseppeTG** [comment]
- [ ] Your pull request title and description need some improvements. The title can be the name of the project you are currently working on ("Hello-Microverse"), and the description can be the steps that you did to achieve your result. 😺 

I'm not sure, but in the title and branch name you put "featers". Maybe you meant "Features"? 😅 (You don't have to change your branch name)

**Comment by GiuseppeTG** [comment]
- [ ] Please create a test.md file and then ignore it with .gitignore 👍 
In your gitignore file you should have something like this:

```
node_modules
test.md
```

Please remove this:
https://github.com/AhmadiGu/Hello_M/blob/e6d45587f1ae179cd3583e6fc6553aced5d245b8/.gitignore#L3-L17

**Review by Abenezer-Tilahun — APPROVED** [review]
Hi @AhmadiGu     , 

Your project is complete .  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Github Flow.
✔️ Good README


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
